import type { NextPage } from "next";
import Head from "next/head";

import Hero from "../components/Sections/Hero";
import Numbers from "../components/Sections/Numbers";
import Advantages from "../components/Sections/Advantages";
import Testimonials from "../components/Sections/Testimonials";
import Prices from "../components/Sections/Prices";
import Footer from "../components/Sections/Footer";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Assests</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Hero />
                <Numbers />
                <Advantages />
                <Prices />
                <Testimonials />
            </main>
            <Footer />
        </div>
    );
};

export default Home;
